version: "3.5"
services:

    php-alpine:
      build: ./docker/php-alpine
      container_name: php-alpine
      stdin_open: true 
      tty: true        
      working_dir: /var/www/html/
      volumes:
        - .:/var/www/html/
      ports:
       - "8001:80"
      extra_hosts:
       - "host.docker.internal:host-gateway"
